### ISSUE TITLE
Push Event to Listening Server

### ISSUE THREAD

**Issue by jrecasens** [KusoKaihatsuSha/gotapo#2]
Hello, thank you for your contribution! I was wondering if it would be possible to send TAPO generated alarms/events to a listening server of my own? For example, send Tapo event notifications to a custom URL (via HTTP or HTTPS).

Thanks!
Javier

**Comment by KusoKaihatsuSha** [comment]
Hello. In theory, you can check the operability of the "ONVIF" protocol, the "CreatePullPointSubscription" functionality.
