### ISSUE TITLE
plgin camera

### ISSUE THREAD

**Issue by Titoune51** [KusoKaihatsuSha/gotapo#3]
Hello,
I have a Tapo C310 camera that I'm trying to get to work with the jeedom camera plugin, but I can't. I used the RTSP address you mention on the forum (rtsp://username:password@ip:554/stream1) but it doesn't work. It seems that the jeedom camera plugin only sends an image stream (5 images/second) and not a video stream. Do you have any idea why this is not working?
Thanks in advance

**Comment by KusoKaihatsuSha** [comment]
Hello.
1) If your device is single-board-ARM-based,  the processor may resets the frequencies and the video stream cannot be more than 5 fps (video as slideshow).
2) Test fps with low quality address: rtsp://username:password@ip:554/stream2
